"""add is_public column to ai_model table

Revision ID: 299467a05195
Revises: 345460bda0c2
Create Date: 2024-02-06 16:42:51.079071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299467a05195'
down_revision: Union[str, None] = '345460bda0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_models', 'is_public')
    # ### end Alembic commands ###
