"""Add authored_id column to dnm table

Revision ID: 34f3aad9a3b6
Revises: 95e157561c16
Create Date: 2024-01-15 09:56:28.647136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f3aad9a3b6'
down_revision: Union[str, None] = '95e157561c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dnm', sa.Column('authored_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dnm', 'authored_id')
    # ### end Alembic commands ###
