"""Add raw_url, clear_url, ready_url columns to dnm table

Revision ID: 38815ab116ab
Revises: 9ce9b54a0698
Create Date: 2024-01-18 10:06:14.611188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38815ab116ab'
down_revision: Union[str, None] = '9ce9b54a0698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dnm', sa.Column('raw_url', sa.String(), nullable=True))
    op.add_column('dnm', sa.Column('clear_url', sa.String(), nullable=True))
    op.add_column('dnm', sa.Column('ready_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dnm', 'raw_url')
    op.drop_column('dnm', 'clear_url')
    op.drop_column('dnm', 'ready_url')
    # ### end Alembic commands ###
