"""Add url column to markers table

Revision ID: 3edf3ca63418
Revises: 38815ab116ab
Create Date: 2024-01-18 10:28:30.823174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edf3ca63418'
down_revision: Union[str, None] = '38815ab116ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markers', 'url')
    # ### end Alembic commands ###
