"""add default public_id and unique constraints

Revision ID: ed117442e378
Revises: 7acdd8790e48
Create Date: 2024-01-24 14:59:14.604952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed117442e378'
down_revision: Union[str, None] = '7acdd8790e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('public_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'api_keys', ['public_id'])
    op.add_column('roles', sa.Column('public_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'roles', ['public_id'])
    op.add_column('users', sa.Column('public_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'users', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'public_id')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_column('roles', 'public_id')
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.drop_column('api_keys', 'public_id')
    # ### end Alembic commands ###
