"""add_url_column_to_markers_table

Revision ID: f2d347b35b0c
Revises: b255fc3b1ac3
Create Date: 2024-01-16 15:03:29.430334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d347b35b0c'
down_revision: Union[str, None] = 'b255fc3b1ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markers', 'url')
    # ### end Alembic commands ###
